services:
  gpt-ssh:
    build: .
    container_name: gpt-ssh
    hostname: got-ssh
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - 2222:22
    volumes:
      - ./ssh/authorized_keys:/home/chatgpt/.ssh/authorized_keys
